# Generated by Django 4.1.3 on 2022-11-30 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=6)),
                ('street_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=30)),
                ('unit_number', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=15)),
                ('colour', models.CharField(max_length=15)),
                ('license_plate', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=20)),
                ('mileage', models.FloatField(max_length=25)),
                ('branch', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='car_branch', to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('car_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('daily_cost', models.FloatField(max_length=10)),
                ('weekly_cost', models.FloatField(max_length=10)),
                ('monthly_cost', models.FloatField(max_length=10)),
                ('late_fee', models.FloatField(max_length=10)),
                ('change_branch_fee', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('drivers_license', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('DOB', models.DateField(null=True)),
                ('gold_member', models.BooleanField(null=True)),
                ('province', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('postal_code', models.CharField(max_length=6, null=True)),
                ('street_number', models.CharField(max_length=10, null=True)),
                ('street_name', models.CharField(max_length=30, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('salt', models.CharField(max_length=255, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('rank', models.CharField(max_length=30, null=True)),
                ('DOB', models.DateField(null=True)),
                ('province', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('postal_code', models.CharField(max_length=6, null=True)),
                ('street_number', models.CharField(max_length=10, null=True)),
                ('street_name', models.CharField(max_length=30, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('works_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, max_length=10, null=True)),
                ('branch_came_from', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_came_from', to='api.branch')),
                ('branch_goes_to', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_goes_to', to='api.branch')),
                ('car', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.car')),
                ('customer', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer')),
                ('employee_given_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
                ('requested_car_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cartype')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='api.cartype'),
        ),
        migrations.CreateModel(
            name='BranchPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
    ]
