# Generated by Django 4.1.1 on 2022-10-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postalcode', models.CharField(max_length=6)),
                ('streetnumber', models.CharField(max_length=10)),
                ('streetname', models.CharField(max_length=30)),
                ('unitnumber', models.CharField(max_length=5)),
            ],
        ),
    ]
