# Generated by Django 4.1.2 on 2022-10-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('rank', models.CharField(max_length=30)),
                ('DOB', models.DateTimeField()),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=6)),
                ('street_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=30)),
                ('unit_number', models.CharField(max_length=5)),
            ],
        ),
    ]
