# Generated by Django 4.1.1 on 2022-10-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='postalcode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='streetname',
            new_name='street_name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='streetnumber',
            new_name='street_number',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='unitnumber',
            new_name='unit_number',
        ),
        migrations.CreateModel(
            name='Branch_Phone_Number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
    ]
