# Generated by Django 4.1.1 on 2022-10-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_postalcode_branch_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='Branch_Phone_Number',
        ),
    ]
