# Generated by Django 4.1.1 on 2022-10-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employeephonenumber'),
        ('api', '0006_branchphonenumber_delete_branch_phone_number'),
    ]

    operations = [
    ]
