# Generated by Django 4.1.1 on 2022-10-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20221008_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('car_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('daily_cost', models.FloatField(max_length=10)),
                ('weekly_cost', models.FloatField(max_length=10)),
                ('monthly_cost', models.FloatField(max_length=10)),
                ('late_fee', models.FloatField(max_length=10)),
                ('change_branch_fee', models.FloatField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='branchphonenumber',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch'),
        ),
        migrations.CreateModel(
            name='CustomerPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=15)),
                ('colour', models.CharField(max_length=15)),
                ('license_plate', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Available', 'Rented'), ('Not Available', 'Not Rented')], max_length=20)),
                ('mileage', models.FloatField(max_length=25)),
                ('branch', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='car_branch', to='api.branch')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='api.cartype')),
            ],
        ),
    ]
