# Generated by Django 4.1.2 on 2022-10-10 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cartype_alter_branchphonenumber_branch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('date_returned', models.DateField()),
                ('total_cost', models.FloatField(max_length=10)),
                ('gold_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer')),
                ('licence_plate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.car')),
            ],
        ),
    ]
