# Generated by Django 4.1.1 on 2022-10-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_employee_works_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='came_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_came_from', to='api.branch'),
        ),
        migrations.AddField(
            model_name='rental',
            name='given_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.employee'),
        ),
        migrations.AddField(
            model_name='rental',
            name='goes_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_goes_to', to='api.branch'),
        ),
        migrations.AddField(
            model_name='rental',
            name='requested_car_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.cartype'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='gold_member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='licence_plate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='api.car'),
        ),
    ]
