# Generated by Django 4.1.2 on 2022-10-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rental_came_from_rental_given_by_rental_goes_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Not Available', 'Rented'), ('Available', 'Not Rented')], max_length=20),
        ),
    ]
