# Generated by Django 4.1.1 on 2022-10-23 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Available', 'Rented'), ('Not Available', 'Not Rented')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerphonenumber',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='works_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch'),
        ),
        migrations.AlterField(
            model_name='employeephonenumber',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='given_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='gold_member',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='licence_plate',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.car'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='requested_car_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cartype'),
        ),
    ]
