# Generated by Django 4.1.1 on 2022-10-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_car_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='unit_number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
