# Generated by Django 4.1.1 on 2022-11-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_branch_unit_number_alter_car_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='came_from',
            new_name='branch_came_from',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='goes_to',
            new_name='branch_goes_to',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='licence_plate',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='gold_member',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='given_by',
            new_name='employee_given_by',
        ),
    ]
